### ISSUE TITLE
startup_rvc.m seems missing

### ISSUE THREAD

**Issue by TheBlune** [rogasus/robotselector#1]
Hey Rogasus,

First of all, good job publishing your Thesis. You adressed several problems I am facing with mine right now. I am doing something similar in Matlab and wanted to investigate your source code. As this error suggests, there seems to be a file missing.

![image](https://user-images.githubusercontent.com/1479817/33166303-1813cc14-d03a-11e7-8406-3deeb11c4282.png)

Edit: 
I figured myself that I need the [Robotics Toolbox by Peter Corke](http://petercorke.com/wordpress/). Unfortunately the current Version 10.2 seems to break the skript. I will try earlier versions if i find some. 

Edit2: I figured it out using Version 9.1 of the Robotics Toolbox. Thanks for your Work there. Did you ever revisit that topic after writing your thesis?

**Comment by rogasus** [comment]
Hey TheBlune,

Sorry for answering after almost a year late. I didn't notice the issue until now. I used robotic toolbox version 9.7. Glad to hear that this may help your work and you figured out the issue by yourself. I haven't  revisited the work because I have no Matlab licence anymore, but I will always keep my mind open for this.
